# Generated by Django 5.1.3 on 2024-11-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("pages", models.IntegerField(default=0)),
                ("description", models.TextField(default="", max_length=100)),
                ("author", models.CharField(max_length=20)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FI", "Fiction"),
                            ("NF", "Non-Fiction"),
                            ("MY", "Mystery"),
                            ("SF", "Science Fiction"),
                            ("FA", "Fantasy"),
                            ("RO", "Romance"),
                            ("HO", "Horror"),
                            ("BI", "Biography"),
                            ("HI", "History"),
                            ("PO", "Poetry"),
                        ],
                        default="FI",
                        max_length=50,
                    ),
                ),
                ("published_date", models.DateField()),
            ],
        ),
    ]
